// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4lzpxRhO1h4JheyFVcqE6gJLwUWiGV4',
    appId: '1:561751215182:web:90e4aba7515f82e373471f',
    messagingSenderId: '561751215182',
    projectId: 'ca12-c40f7',
    authDomain: 'ca12-c40f7.firebaseapp.com',
    storageBucket: 'ca12-c40f7.firebasestorage.app',
    measurementId: 'G-5SE09TLJQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQLbf_wRn84Hyg0yncgCWTujyMSf0n8I',
    appId: '1:561751215182:android:d35ea4e2aa8a280a73471f',
    messagingSenderId: '561751215182',
    projectId: 'ca12-c40f7',
    storageBucket: 'ca12-c40f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzuH-6b79fa0GC-UzZqmBlmnlrPBQrJS0',
    appId: '1:561751215182:ios:80fa82a3d97ba61b73471f',
    messagingSenderId: '561751215182',
    projectId: 'ca12-c40f7',
    storageBucket: 'ca12-c40f7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzuH-6b79fa0GC-UzZqmBlmnlrPBQrJS0',
    appId: '1:561751215182:ios:80fa82a3d97ba61b73471f',
    messagingSenderId: '561751215182',
    projectId: 'ca12-c40f7',
    storageBucket: 'ca12-c40f7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa4lzpxRhO1h4JheyFVcqE6gJLwUWiGV4',
    appId: '1:561751215182:web:68991ec3ea14825b73471f',
    messagingSenderId: '561751215182',
    projectId: 'ca12-c40f7',
    authDomain: 'ca12-c40f7.firebaseapp.com',
    storageBucket: 'ca12-c40f7.firebasestorage.app',
    measurementId: 'G-7E6SXH5QK1',
  );
}
